sudo: required
language: node_js
services:
  - docker
  - mongodb
node_js:
  - 10
install:
  - npm install
before_script:
  - sudo service mysql stop
  - docker-compose version
  - docker-compose up -d
script:
  - gulp init
  - gulp lint
  - gulp test
after_script:
  - docker-compose down
